# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/zgh/learn_files/LoongArch_learning/exp6/mycpu_env/soc_verify/soc_dram/run_vivado/constraints/soc_lite_top.xdc

# IP: /home/zgh/learn_files/LoongArch_learning/exp6/mycpu_env/soc_verify/soc_dram/rtl/xilinx_ip/data_ram/data_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_ram || ORIG_REF_NAME==data_ram} -quiet] -quiet

# XDC: /home/zgh/learn_files/LoongArch_learning/exp6/mycpu_env/soc_verify/soc_dram/rtl/xilinx_ip/data_ram/data_ram_ooc.xdc
