set_property SRC_FILE_INFO {cfile:/home/zgh/learn_files/LoongArch_learning/exp6/mycpu_env/soc_verify/soc_dram/rtl/xilinx_ip/clk_pll/clk_pll/clk_pll_in_context.xdc rfile:../../../../../../../rtl/xilinx_ip/clk_pll/clk_pll/clk_pll_in_context.xdc id:1 order:EARLY scoped_inst:pll.clk_pll} [current_design]
set_property SRC_FILE_INFO {cfile:/home/zgh/learn_files/LoongArch_learning/exp6/mycpu_env/soc_verify/soc_dram/rtl/xilinx_ip/inst_ram/inst_ram/inst_ram_in_context.xdc rfile:../../../../../../../rtl/xilinx_ip/inst_ram/inst_ram/inst_ram_in_context.xdc id:2 order:EARLY scoped_inst:inst_ram} [current_design]
set_property SRC_FILE_INFO {cfile:/home/zgh/learn_files/LoongArch_learning/exp6/mycpu_env/soc_verify/soc_dram/run_vivado/constraints/soc_lite_top.xdc rfile:../../../../../../constraints/soc_lite_top.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:/home/zgh/learn_files/LoongArch_learning/exp6/mycpu_env/soc_verify/soc_dram/run_vivado/project/loongson.runs/synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:4} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk [get_ports clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name pll.clk_pll/cpu_clk -source [get_ports clk] -edges {1 2 3} -edge_shift {0.000 5.000 10.000} [get_pins pll.clk_pll/cpu_clk]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name pll.clk_pll/timer_clk -source [get_ports clk] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_pins pll.clk_pll/timer_clk]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports clk]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports clk]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells pll.clk_pll]
current_instance inst_ram
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells inst_ram]
set_property src_info {type:XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets clk]
set_property src_info {type:XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]
set_property src_info {type:XDC file:3 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property src_info {type:XDC file:3 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports resetn]
set_property src_info {type:XDC file:3 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[*]}]
set_property src_info {type:XDC file:3 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led_rg0[*]}]
set_property src_info {type:XDC file:3 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led_rg1[*]}]
set_property src_info {type:XDC file:3 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {num_a_g[*]}]
set_property src_info {type:XDC file:3 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {num_csn[*]}]
set_property src_info {type:XDC file:3 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[*]}]
set_property src_info {type:XDC file:3 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_key_col[*]}]
set_property src_info {type:XDC file:3 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_key_row[*]}]
set_property src_info {type:XDC file:3 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_step[*]}]
set_property src_info {type:XDC file:3 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {num_data[*]}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells data_ram]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells pll.clk_pll]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells inst_ram]
